### ISSUE TITLE
object is not a function

### ISSUE THREAD

**Issue by ChitaGideon** [keystonejs/grappling-hook#10]
```
var grappling = require('grappling-hook');

var instance = grappling.create(); // create an instance

instance.addHooks({ // declare the hookable methods
    save: function(done){
        console.log('save!');
        done && done();
    }
});

instance.pre('save', function(){ //allow middleware to be registered for a hook
    console.log('saving!');
}).post('save', function(){
    console.log('saved!');
});

instance.save();
```

I just copy this example and run.
somehow something goes wrong

```
TypeError: object is not a function

    at safeNext (...node_modules/grappling-hook/index.js:74:4)

    at ...node_modules/grappling-hook/index.js:116:4

    at ...node_modules/grappling-hook/node_modules/async/lib/async.js:154:25

    at async.eachSeries.asyncFinished (...node_modules/grappling-hook/index.js:111:5)

    at iterate (...node_modules/grappling-hook/node_modules/async/lib/async.js:146:13)

    at ...node_modules/grappling-hook/node_modules/async/lib/async.js:157:25

    at ...node_modules/grappling-hook/index.js:71:5

    at process._tickDomainCallback (node.js:381:11)
```

**Comment by creynders** [comment]
Thanks, I'll look into it ASAP!

**Comment by creynders** [comment]
Ah, yes of course. The last line should be 

```
instance.save(function(err){
  console.log('all done!');
});
```

Since we're registering `save` as an async method. Will update the docs!
